### ISSUE TITLE
Uncaught Error: Cannot find deployed address: MetaCoin not deployed or address not set

### ISSUE THREAD

**Issue by bneiluj** [ConsenSys/truffle-webpack-demo#6]
## Issue

Get an error message on chrome dev tool `Uncaught Error: Cannot find deployed address: MetaCoin not deployed or address not set` when updating the default balance to another value. 

## Steps to Reproduce

1. Start testrpc
2. Starts the development server 
3. Go to http://localhost:3000/
4. Change the value of the default balance in contracts/MetaCoin.sol.
5. Wait for hot reload and see error message in the chrome dev tool. 

## Expected Behavior

To refresh the value on the page.

## Actual Results

After changing the value of the default balance in contracts/MetaCoin.sol from 10000 to another integer (like 50000), the value is not always updated and a message error is displayed on the console: 
`Uncaught Error: Cannot find deployed address: MetaCoin not deployed or address not set`

Restarting the testrpc and dev server fixes the issue. 

Looks like it comes from: 

```
Contract.deployed = function() {
    if (!this.address) {
      throw new Error("Cannot find deployed address: MetaCoin not deployed or address not set.");
    }

    return this.at(this.address);
  };
```

## Environment

* Operating System:Mac Os El Capitan 10.11.6
* Truffle version: v2.0.4
* Testrpc version: v3.0.0
* Ethereum client:Geth Version: 1.4.18-stable-c72f5459
* node version: v4.6.0
* npm version: 2.15.9

**Comment by johnmcdowall** [comment]
Ok this should be fixed in  bad94a5. It was caused by the `truffle-solidity-loader` not always re-running the migrations after a contract change.

**Comment by deefactorial** [comment]
I can confirm this error still exists, after your changes.

## Environment

* Operating System: Ubuntu 14.04
* Truffle version: v2.1.0
* Testrpc version: v3.0.0
* Ethereum client: Geth Version: 1.4.17-stable-5a6008e0
* node version: v5.0.0
* npm version:v3.8.2

**Comment by johnmcdowall** [comment]
@deefactorial Do the migrations re-run when you change the contract?

**Comment by bneiluj** [comment]
@johnmcdowall The hot reload is triggered but nothing is shown on the screen as ```MetaCoin.sol:311 Uncaught Error: Cannot find deployed address: MetaCoin not deployed or address not set.``` is fired. 
It crashed the page if you reload it. 
<img width="703" alt="screen shot 2016-10-27 at 11 35 35" src="https://cloud.githubusercontent.com/assets/3680497/19764245/f6299000-9c39-11e6-9a6e-c85dc1c1d2fb.png">

**Comment by deefactorial** [comment]
Yes it does,

here is console log from the npm start command after the change.
```sh
Compiling...
[TRUFFLE SOLIDITY] Writing temporary contract build artifacts to /home/deefactorial/development/js/truffle-webpack-demo/.truffle-solidity-loader
[TRUFFLE SOLIDITY] Compiling ConvertLib.sol...
[TRUFFLE SOLIDITY] Compiling MetaCoin.sol...
[TRUFFLE SOLIDITY] Writing artifacts to ./.truffle-solidity-loader
[TRUFFLE SOLIDITY] COMPILATION FINISHED
[TRUFFLE SOLIDITY] RUNNING MIGRATIONS
Compiled successfully!

The app is running at http://localhost:3000/
```

here is the console log from chrome:
```
[HMR] Waiting for update signal from WDS...
webpack:///./~/react/lib/ReactDOM.js?:75 Download the React DevTools for a better development experience: https://fb.me/react-devtools
client:22 [WDS] Hot Module Replacement enabled.
2client:25 [WDS] App updated. Recompiling...
client:90 [WDS] App hot update...
dev-server.js:55 [HMR] Checking for updates on the server...
index.js:81 [React Transform HMR] Patching SendCoin
index.js:81 [React Transform HMR] Patching AccountListContainer
log-apply-result.js:20 [HMR] Updated modules:
log-apply-result.js:22 [HMR]  - 413
log-apply-result.js:22 [HMR]  - 410
log-apply-result.js:22 [HMR]  - 406
dev-server.js:41 [HMR] App is up to date.
22MetaCoin.sol:311 Uncaught Error: Cannot find deployed address: MetaCoin not deployed or address not set.
```

**Comment by ted-piotrowski** [comment]
Contract reloading works with version 0.0.8 of the truffle-solidity-loader. I'm not sure if that's an actual release since it has some debugging console.log's hanging around, but it is available on NPM right now.

For anyone having issues, bump the truffle-solidity-loader dependency to 0.0.8 in the projects `package.json`

**Comment by bneiluj** [comment]
```truffle-solidity-loader dependency``` on  ```v0.0.8``` fix the isue by forcing the migrations to re-run.  
```migrationOpts.reset = true``` // Force the migrations to re-run

Change made by @johnmcdowall

**Comment by chinmayrane** [comment]
What's the solution to this? Should I update TRuffle again or change the part where I call the smart contract in the app.js file?

**Comment by johnmcdowall** [comment]
The solution is to make sure you're using at least `0.0.8` of `truffle-solidity-loader`...
